logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/przychodnia
    username: root
    password: nowe123
  jpa:
    generate-ddl: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 1

server:
  port: 8089